name: CI
on: [push, workflow_dispatch]
jobs:
  unit:
    strategy:
      matrix:
        node: [ '14', '16', '18' ]
    runs-on: 'ubuntu-latest'
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: yarn
        run: yarn
      - name: yarn run test-unit
        run: yarn run test-unit
  mysql:
    needs: [unit]
    strategy:
      matrix:
        node: [ '14', '16', '18']
        mysql: [ '5.6', '5.7', '8' ]
    runs-on: 'ubuntu-latest'
    name: Node ${{ matrix.node }} Mysql ${{ matrix.mysql }}
    steps:
      - name: Setup Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.mysql }}
          mysql database: 'queue'
          mysql root password: 'root'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: yarn
        run: yarn
      - name: yarn run test-mysql
        run: yarn run test-mysql
  redis:
    needs: [unit, mysql]
    strategy:
      matrix:
        node: [ '14', '16', '18' ]
        redis: [ '3', '4', '5', '6', '7' ]
    runs-on: 'ubuntu-latest'
    name: Node ${{ matrix.node }} Redis ${{ matrix.redis }}
    steps:
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: ${{ matrix.redis }}
          number of databases: 1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: yarn
        run: yarn
      - name: yarn run test-redis
        run: yarn run test-redis
  sqlite3:
    needs: [unit, mysql, redis]
    strategy:
      matrix:
        node: [ '14', '16', '18' ]
    runs-on: 'ubuntu-latest'
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: yarn
        run: yarn
      - name: yarn run test-sqlite3
        run: yarn run test-sqlite3
